// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzmR5BsyqYlPiV0zFUUJ0w_Ae3X9kBNGE',
    appId: '1:902773632002:android:d3c30e61301cfb52dc0b1b',
    messagingSenderId: '902773632002',
    projectId: 'safelist-5b99d',
    storageBucket: 'safelist-5b99d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeJAVTsfuKPTUR86Njqq7qquSB-4KmJsc',
    appId: '1:902773632002:ios:6f92e592526d6b53dc0b1b',
    messagingSenderId: '902773632002',
    projectId: 'safelist-5b99d',
    storageBucket: 'safelist-5b99d.firebasestorage.app',
    iosBundleId: 'com.example.safelist',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDfuTZF_LnkNUFZhUORM9XpX8IblFrhY4',
    appId: '1:902773632002:web:b3b28ff41997a79bdc0b1b',
    messagingSenderId: '902773632002',
    projectId: 'safelist-5b99d',
    authDomain: 'safelist-5b99d.firebaseapp.com',
    storageBucket: 'safelist-5b99d.firebasestorage.app',
    measurementId: 'G-4XJQ6KLHDT',
  );

}
